[web]
web1 ansible_host=127.0.0.1 ansible_port=2371

[web:vars]
ansible_user=secops
ansible_ssh_private_key_file=/tmp/cap18-lab/key
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
